name: auth
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  protobuf: ^3.1.0
  grpc: ^3.2.4
  stormberry: ^0.14.0
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.3
  encrypt: 5.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
